/**
* @{
* @file cfg_cal.h
* @brief This header file generates variable, structure, and enumeration definitions related to vehicle configuration based on an Excel table.
* @author HUALEI
* @date 2026-01-13 15:57:09
* @table vehicle_config_word_list_20251218.xlsx (Sheet: n80)
* @copyright (C) 2025 Auto-link.
*                Unauthorized reproduction, distribution, and use of this file, as well as disclosure of its contents to others, are prohibited.
*                Violators will be held liable. All rights reserved in case of patent, utility model, or design authorization.
* @}
**/

/**
* DO NOT MODIFY THIS FILE MANUALLY!!!
* This file is automatically generated by the script.
**/
#ifndef _CFG_CAL_H /* _CFG_CAL_H */
#define _CFG_CAL_H /* _CFG_CAL_H */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
#include <stdint.h>

/**
* DID: 0xf011
* DID LEN: 24
* DID DESC(EN): Vehicle Configuration Data
* DID DESC(EN):
**/
struct Did0xf011
{
    uint8_t VEHICLE_VARIANT : 4; // Byte 0
    uint8_t LANGUAGE : 4; // Byte 0
    uint8_t REVERSE_VIEW_CONFIG : 2; // Byte 1
    uint8_t RADAR_CONFIG : 3; // Byte 1
    uint8_t TRANSPARENT_CHASSIS : 1; // Byte 1
    uint8_t AUTOMATIC_PARKING_ASSIST : 1; // Byte 1
    uint8_t RESERVED_1 : 1; // Byte 1
    uint8_t ACC : 1; // Byte 2
    uint8_t TJA_ICA : 1; // Byte 2
    uint8_t SLKA : 1; // Byte 2
    uint8_t ASL : 1; // Byte 2
    uint8_t FCW : 1; // Byte 2
    uint8_t AEB : 1; // Byte 2
    uint8_t LKA : 1; // Byte 2
    uint8_t ELK : 1; // Byte 2
    uint8_t SLA : 1; // Byte 3
    uint8_t TSI_TSR : 1; // Byte 3
    uint8_t TLA : 1; // Byte 3
    uint8_t HMA : 1; // Byte 3
    uint8_t MOD : 1; // Byte 3
    uint8_t ISA : 1; // Byte 3
    uint8_t RESERVED_2 : 1; // Byte 3
    uint8_t RESERVED_3 : 1; // Byte 3
    uint8_t BSD_LCA : 1; // Byte 4
    uint8_t DOW : 2; // Byte 4
    uint8_t RCTA : 1; // Byte 4
    uint8_t RCTB : 1; // Byte 4
    uint8_t RCW : 1; // Byte 4
    uint8_t SUSPENSION_STIFFNESS_ADJUST : 1; // Byte 4
    uint8_t RESERVED_4 : 1; // Byte 4
    uint8_t AIR_CONDITIONING_ZONES : 2; // Byte 5
    uint8_t PRE_VENTILATION : 1; // Byte 5
    uint8_t TEMPORARY_LEAVE_MODE : 1; // Byte 5
    uint8_t INSTANT_COOL : 1; // Byte 5
    uint8_t INSTANT_HEAT : 1; // Byte 5
    uint8_t OUTSIDE_TEMP_DISPLAY : 1; // Byte 5
    uint8_t AIR_CONDITIONING_MODE : 1; // Byte 5
    uint8_t ICC_AUDIO_EFFECT_TYPE : 1; // Byte 6
    uint8_t VIRTUAL_AVATAR : 1; // Byte 6
    uint8_t DISPLAY_SCREEN_SIZE : 2; // Byte 6
    uint8_t VOICE_ZONES : 3; // Byte 6
    uint8_t TBOX : 1; // Byte 6
    uint8_t DVR : 1; // Byte 7
    uint8_t DMS_CAMERA : 1; // Byte 7
    uint8_t BLUETOOTH_KEY_AUTO_LOGIN : 1; // Byte 7
    uint8_t NFC_CARD : 1; // Byte 7
    uint8_t APP_MARKET : 1; // Byte 7
    uint8_t EXTERNAL_SPEAKER : 2; // Byte 7
    uint8_t ONLINE_AUDIO : 1; // Byte 7
    uint8_t BABY_SLEEP_MODE : 1; // Byte 8
    uint8_t FRONT_SEAT_REST_MODE : 1; // Byte 8
    uint8_t MEDITATION_MODE : 1; // Byte 8
    uint8_t COMMUTE_MODE : 1; // Byte 8
    uint8_t REFRESH_MODE : 1; // Byte 8
    uint8_t VENTILATION_MODE : 1; // Byte 8
    uint8_t CAMPING_MODE : 1; // Byte 8
    uint8_t MILEAGE_SURPRISE_MODE : 1; // Byte 8
    uint8_t DEFAULT_RADIO_STANDARD : 4; // Byte 9
    uint8_t SPEAKER_COUNT : 3; // Byte 9
    uint8_t AMPLIFIER_TYPE : 1; // Byte 9
    uint8_t INTELLIGENT_SCENE_MODE : 1; // Byte 10
    uint8_t ONE_TOUCH_WINDOW_CONTROL : 1; // Byte 10
    uint8_t WELCOME_LIGHTING : 1; // Byte 10
    uint8_t MIRROR_FOLDING : 1; // Byte 10
    uint8_t MIRROR_MEMORY : 1; // Byte 10
    uint8_t ELECTRIC_SUNSHADE : 1; // Byte 10
    uint8_t POWER_TAILGATE : 1; // Byte 10
    uint8_t FRONT_WINDSHIELD_HEATING : 1; // Byte 10
    uint8_t DRIVER_SEAT_MEMORY : 1; // Byte 11
    uint8_t PASSENGER_SEAT_MEMORY : 1; // Byte 11
    uint8_t SECOND_ROW_LEFT_SEAT_MEMORY : 1; // Byte 11
    uint8_t SECOND_ROW_RIGHT_SEAT_MEMORY : 1; // Byte 11
    uint8_t THIRD_ROW_SEAT_SLIDING_ELECTRIC : 1; // Byte 11
    uint8_t RESERVED_5 : 1; // Byte 11
    uint8_t RESERVED_6 : 1; // Byte 11
    uint8_t RESERVED_7 : 1; // Byte 11
    uint8_t SMART_ENTRY_SWITCH : 1; // Byte 12
    uint8_t POWER_TAILGATE_SMART_ENTRY_SWITCH : 1; // Byte 12
    uint8_t AUTO_HEADLIGHT : 1; // Byte 12
    uint8_t OUTSIDE_MIRROR_HEATING : 1; // Byte 12
    uint8_t AMBIENT_LIGHTING : 1; // Byte 12
    uint8_t STEERING_WHEEL_HEATING : 1; // Byte 12
    uint8_t VEHICLE_REFRIGERATOR : 1; // Byte 12
    uint8_t BATTERY_SENSOR_TYPE : 1; // Byte 12
    uint8_t DRIVE_MODE : 1; // Byte 13
    uint8_t CRUISE_CONTROL : 1; // Byte 13
    uint8_t TPMS_TYPE : 1; // Byte 13
    uint8_t TIRE_SIZE : 2; // Byte 13
    uint8_t MANDATORY_OVERSPEED_WARNING : 1; // Byte 13
    uint8_t RAIN_SENSING_WIPERS : 1; // Byte 13
    uint8_t RESERVED_8 : 1; // Byte 13
    uint8_t ONE_PEDAL_MODE : 1; // Byte 14
    uint8_t ECO_DRIVE_MODE : 1; // Byte 14
    uint8_t SPORT_DRIVE_MODE : 1; // Byte 14
    uint8_t COMFORT_DRIVE_MODE : 1; // Byte 14
    uint8_t EXTREME_ECO_MODE : 1; // Byte 14
    uint8_t SLIPPERY_ROAD_MODE : 1; // Byte 14
    uint8_t ADAPTIVE_DRIVE_MODE : 1; // Byte 14
    uint8_t PERSONALIZED_DRIVE_MODE : 1; // Byte 14
    uint8_t CARPLAY : 1; // Byte 15
    uint8_t ANDROID_AUTO : 1; // Byte 15
    uint8_t YILIAN : 1; // Byte 15
    uint8_t CARLINK : 1; // Byte 15
    uint8_t HICAR : 1; // Byte 15
    uint8_t AQS : 1; // Byte 15
    uint8_t IN_CABIN_PM2_5_DISPLAY : 1; // Byte 15
    uint8_t WATER_ION : 1; // Byte 15
    uint8_t DRIVER_SEAT_HEATING : 1; // Byte 16
    uint8_t PASSENGER_SEAT_HEATING : 1; // Byte 16
    uint8_t SECOND_ROW_LEFT_SEAT_HEATING : 1; // Byte 16
    uint8_t SECOND_ROW_RIGHT_SEAT_HEATING : 1; // Byte 16
    uint8_t THIRD_ROW_LEFT_SEAT_HEATING : 1; // Byte 16
    uint8_t THIRD_ROW_RIGHT_SEAT_HEATING : 1; // Byte 16
    uint8_t RESERVED_9 : 1; // Byte 16
    uint8_t RESERVED_10 : 1; // Byte 16
    uint8_t DRIVER_SEAT_VENTILATION : 1; // Byte 17
    uint8_t PASSENGER_SEAT_VENTILATION : 1; // Byte 17
    uint8_t SECOND_ROW_LEFT_SEAT_VENTILATION : 1; // Byte 17
    uint8_t SECOND_ROW_RIGHT_SEAT_VENTILATION : 1; // Byte 17
    uint8_t THIRD_ROW_LEFT_SEAT_VENTILATION : 1; // Byte 17
    uint8_t THIRD_ROW_RIGHT_SEAT_VENTILATION : 1; // Byte 17
    uint8_t RESERVED_11 : 1; // Byte 17
    uint8_t RESERVED_12 : 1; // Byte 17
    uint8_t DRIVER_SEAT_MASSAGE : 1; // Byte 18
    uint8_t PASSENGER_SEAT_MASSAGE : 1; // Byte 18
    uint8_t SECOND_ROW_LEFT_SEAT_MASSAGE : 1; // Byte 18
    uint8_t SECOND_ROW_RIGHT_SEAT_MASSAGE : 1; // Byte 18
    uint8_t FRONT_SEAT_MASSAGE_POINTS : 2; // Byte 18
    uint8_t SECOND_ROW_SEAT_MASSAGE_POINTS : 2; // Byte 18
    uint8_t CENTRAL_SCREEN_MANUFACTURER : 2; // Byte 19
    uint8_t CEILING_SCREEN_SIZE : 2; // Byte 19
    uint8_t SENTRY_MODE : 1; // Byte 19
    uint8_t FACIAL_RECOGNITION : 1; // Byte 19
    uint8_t RESERVED_13 : 1; // Byte 19
    uint8_t RESERVED_14 : 1; // Byte 19
    uint8_t FRONT_WIRELESS_CHARGING : 2; // Byte 20
    uint8_t SECOND_ROW_WIRELESS_CHARGING : 2; // Byte 20
    uint8_t FRONT_HEADREST_SPEAKERS : 2; // Byte 20
    uint8_t SECOND_ROW_LEFT_HEADREST_SPEAKER : 1; // Byte 20
    uint8_t SECOND_ROW_RIGHT_HEADREST_SPEAKER : 1; // Byte 20
    uint8_t SECOND_ROW_LEFT_ZERO_GRAVITY_SEAT : 1; // Byte 21
    uint8_t SECOND_ROW_RIGHT_ZERO_GRAVITY_SEAT : 1; // Byte 21
    uint8_t RESERVED_15 : 1; // Byte 21
    uint8_t RESERVED_16 : 1; // Byte 21
    uint8_t RESERVED_17 : 1; // Byte 21
    uint8_t RESERVED_18 : 1; // Byte 21
    uint8_t RESERVED_19 : 1; // Byte 21
    uint8_t RESERVED_20 : 1; // Byte 21
    uint8_t RESERVED_21 : 1; // Byte 22
    uint8_t RESERVED_22 : 1; // Byte 22
    uint8_t RESERVED_23 : 1; // Byte 22
    uint8_t RESERVED_24 : 1; // Byte 22
    uint8_t RESERVED_25 : 1; // Byte 22
    uint8_t RESERVED_26 : 1; // Byte 22
    uint8_t RESERVED_27 : 1; // Byte 22
    uint8_t RESERVED_28 : 1; // Byte 22
    uint8_t ENGLISH_CHINESE_OPTION : 1; // Byte 23
    uint8_t AIRBAG_DISABLING : 1; // Byte 23
    uint8_t RESERVED_29 : 1; // Byte 23
    uint8_t RESERVED_30 : 1; // Byte 23
    uint8_t RESERVED_31 : 1; // Byte 23
    uint8_t RESERVED_32 : 1; // Byte 23
    uint8_t RESERVED_33 : 1; // Byte 23
    uint8_t RESERVED_34 : 1; // Byte 23
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* _CFG_CAL_H */