import openpyxl
import datetime
import os
import argparse
import json

def find_excel_files(directory):
    """
    在指定目录中查找所有Excel文件
    :param directory: 要查找的目录
    :return: Excel文件路径列表
    """
    excel_files = []
    if os.path.exists(directory):
        for file in os.listdir(directory):
            if file.endswith('.xlsx'):
                excel_files.append(os.path.join(directory, file))
    return sorted(excel_files)

def read_config(config_file):
    """
    读取配置文件
    :param config_file: 配置文件路径
    :return: 配置字典
    :raises: 如果配置文件无法读取，程序将退出
    """
    try:
        with open(config_file, 'r', encoding='utf-8') as f:
            return json.load(f)
    except Exception as e:
        print(f"错误：无法读取配置文件 {config_file}: {e}")
        print("配置文件必须存在且格式正确，程序将退出。")
        exit(1)

def generate_header_file(excel_file, output_file, sheet_name, bit_order="reverse"):
    """
    为指定的Excel文件和工作表生成头文件
    :param excel_file: Excel文件路径
    :param output_file: 输出文件路径
    :param sheet_name: 要处理的工作表名称
    :param bit_order: bit位排序方式，"reverse"表示倒序，"normal"表示正序
    """
    # 获取当前日期和时间
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # 定义头文件的基本结构，包含注释信息
    header_content = [
        "/**",
        "* @{",
        f"* @file {os.path.basename(output_file)}",
        "* @brief This header file generates variable, structure, and enumeration definitions related to vehicle configuration based on an Excel table.",
        f"* @author HUALEI",
        f"* @date {now}",
        f"* @table {os.path.basename(excel_file)} (Sheet: {sheet_name})",
        "* @copyright (C) 2025 Auto-link.",
        "*                Unauthorized reproduction, distribution, and use of this file, as well as disclosure of its contents to others, are prohibited.",
        "*                Violators will be held liable. All rights reserved in case of patent, utility model, or design authorization.",
        "* @}",
        "**/",
        "",
        "/**",
        "* DO NOT MODIFY THIS FILE MANUALLY!!!",
        "* This file is automatically generated by the script.",
        "**/",
        f"#ifndef _CFG_CAL_H /* _CFG_CAL_H */",
        f"#define _CFG_CAL_H /* _CFG_CAL_H */",
        "",
        "#ifdef __cplusplus",
        "extern \"C\" {",
        "#endif /* __cplusplus */",
        "#include <stdint.h>",
        "",
        "/**",
        "* DID: 0xf011",
        "* DID LEN: 24",
        "* DID DESC(EN): Vehicle Configuration Data",
        "* DID DESC(EN):",
        "**/",
        "struct Did0xf011",
        "{",
    ]

    # 打开 Excel 文件
    workbook = openpyxl.load_workbook(excel_file)
    sheet = workbook[sheet_name]

    # 全局 RESERVED_ 计数器
    reserved_counter = 1

    # 用于存储每个 byte 内的变量信息
    byte_variables = {}

    # 从第二行开始遍历，跳过表头
    for row in sheet.iter_rows(min_row=2, values_only=True):
        # 确保前四列数据不为 None 且不为空字符串
        if any(cell is None or cell == "" for cell in row[:4]):
            continue

        byte_num = row[0]  # A 列：BYTE
        bit_width = row[1]  # B 列：BIT
        var_type = row[2]  # C 列：TYPE
        var_name = row[3]  # D 列：CONGIF_ITEM_NAME

        try:
            byte_num = int(byte_num)
            if not 0 <= byte_num <= 23:
                print(f"Warning: Byte number {byte_num} is not in the range of 0~23, skipping variable {var_name}")
                continue
        except ValueError:
            print(f"Warning: Byte number {byte_num} is not a valid integer, skipping variable {var_name}")
            continue

        try:
            bit_width = int(bit_width)
            if not 1 <= bit_width <= 8:
                print(f"Warning: Bit width {bit_width} is not in the range of 1~8, skipping variable {var_name}")
                continue
        except ValueError:
            print(f"Warning: Bit width {bit_width} is not a valid integer, skipping variable {var_name}")
            continue

        # 处理 RESERVED_ 名称
        if var_name == "RESERVED_":
            new_var_name = f"RESERVED_{reserved_counter}"
            reserved_counter += 1
            var_name = new_var_name

        # 将变量信息添加到对应的 byte 列表中
        if byte_num not in byte_variables:
            byte_variables[byte_num] = []
        byte_variables[byte_num].append((var_type, var_name, bit_width))

    # 按 byte 顺序遍历，根据bit_order参数决定是否倒序添加变量
    for byte_num in sorted(byte_variables.keys()):
        variables = byte_variables[byte_num]
        if bit_order == "reverse":
            variables = reversed(variables)

        for var_type, var_name, bit_width in variables:
            header_content.append(f"    {var_type} {var_name} : {bit_width}; // Byte {byte_num}")

    header_content.extend([
        "};",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif /* __cplusplus */",
        "",
        "#endif /* _CFG_CAL_H */"
    ])

    # 将内容写入头文件
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(header_content))

    print(f"头文件已成功生成: {output_file} (Sheet: {sheet_name}, 排序方式: {'倒序(bit7~bit0)' if bit_order == 'reverse' else '正序(bit0~bit7)'})")

if __name__ == "__main__":
    # 解析命令行参数
    parser = argparse.ArgumentParser(description='车辆配置头文件生成工具')
    parser.add_argument('--bit-order', choices=['reverse', 'normal'], default='reverse',
                        help='Byte内变量的排序方式：reverse（倒序，默认，bit7~bit0），normal（正序，bit0~bit7）')
    args = parser.parse_args()

    # 定义目录
    table_dir = "table"
    output_dir = "output"
    config_file = "config.json"

    # 读取配置文件 - 如果失败会直接退出程序
    config = read_config(config_file)

    # 确保输出目录存在
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # 查找所有Excel文件
    excel_files = find_excel_files(table_dir)

    if not excel_files:
        print(f"在 {table_dir} 文件夹中未找到Excel文件(.xlsx)")
        exit(1)

    # 列出找到的Excel文件
    print("找到以下Excel文件：")
    for i, file in enumerate(excel_files, 1):
        print(f"{i}. {os.path.basename(file)}")

    # 让用户选择要导入的Excel文件
    while True:
        try:
            choice = int(input("请输入要导入的Excel文件序号: "))
            if 1 <= choice <= len(excel_files):
                selected_file = excel_files[choice - 1]
                break
            else:
                print(f"输入无效，请输入1到{len(excel_files)}之间的序号")
        except ValueError:
            print("输入无效，请输入数字序号")

    # 打开Excel文件，获取所有工作表名称
    workbook = openpyxl.load_workbook(selected_file)
    sheet_names = workbook.sheetnames

    print(f"\n正在处理文件: {os.path.basename(selected_file)}")

    # 列出所有工作表供用户选择
    print("\n文件包含以下工作表：")
    for i, sheet_name in enumerate(sheet_names, 1):
        print(f"{i}. {sheet_name}")

    # 让用户选择要处理的工作表
    while True:
        try:
            sheet_choice = int(input("请输入要处理的工作表序号: "))
            if 1 <= sheet_choice <= len(sheet_names):
                selected_sheet = sheet_names[sheet_choice - 1]
                break
            else:
                print(f"输入无效，请输入1到{len(sheet_names)}之间的序号")
        except ValueError:
            print("输入无效，请输入数字序号")

    # 根据配置文件和工作表名称选择bit位排序方式
    sheet_name_lower = selected_sheet.lower()
    current_bit_order = args.bit_order
    config_used = False

    # 从配置文件中获取排序方式
    if sheet_name_lower in [sheet.lower() for sheet in config.get("reverse_sheets", [])]:
        current_bit_order = 'reverse'
        config_used = True
    elif sheet_name_lower in [sheet.lower() for sheet in config.get("normal_sheets", [])]:
        current_bit_order = 'normal'
        config_used = True

    # 根据是否使用了配置文件打印不同的信息
    if config_used:
        print(f"从配置文件中读取到工作表 {selected_sheet} 的排序方式")
    else:
        print(f"配置文件中未指定工作表 {selected_sheet} 的排序方式，使用命令行参数或默认值")

    print(f"\n正在处理工作表: {selected_sheet}")
    print(f"使用的bit位排序方式: {'倒序(bit7~bit0)' if current_bit_order == 'reverse' else '正序(bit0~bit7)'}")

    # 为当前工作表创建输出文件夹
    sheet_output_dir = os.path.join(output_dir, selected_sheet)
    if not os.path.exists(sheet_output_dir):
        os.makedirs(sheet_output_dir)

    # 定义输出文件路径
    output_file = os.path.join(sheet_output_dir, "cfg_cal.h")

    # 生成头文件
    generate_header_file(selected_file, output_file, selected_sheet, current_bit_order)

    print("\n工作表已处理完成！")