"""cfg_cal.h 代码生成器。

接收内存中的 ConfigItem 列表，生成 cfg_cal.h 头文件，
不直接读取 Excel 文件。
"""

import datetime
import os
import re
from collections import OrderedDict


_RE_NUMBERED_RESERVED = re.compile(r"^RESERVED_(\d+)$")


def generate_cfg_cal_h(items, output_file, project_name, bit_order="reverse"):
    """Generate cfg_cal.h from a list of ConfigItem objects.

    Args:
        items: list of ConfigItem with english_name filled
        output_file: path to write cfg_cal.h
        project_name: project name for header comment
        bit_order: "reverse" (bit7→bit0) or "normal" (bit0→bit7)
    """
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    max_byte = 23
    if items:
        max_byte = max(max_byte, max(i.byte for i in items))
    did_len = max_byte + 1

    header_content = [
        "/**",
        "* @{",
        f"* @file {os.path.basename(output_file)}",
        "* @brief This header file generates variable, structure, and enumeration "
        "definitions related to vehicle configuration based on an Excel table.",
        f"* @author HUALEI",
        f"* @date {now}",
        f"* @project {project_name}",
        "* @copyright (C) 2025 Auto-link.",
        "*                Unauthorized reproduction, distribution, and use of this "
        "file, as well as disclosure of its contents to others, are prohibited.",
        "*                Violators will be held liable. All rights reserved in case "
        "of patent, utility model, or design authorization.",
        "* @}",
        "**/",
        "",
        "/**",
        "* DO NOT MODIFY THIS FILE MANUALLY!!!",
        "* This file is automatically generated by the script.",
        "**/",
        "#ifndef _CFG_CAL_H /* _CFG_CAL_H */",
        "#define _CFG_CAL_H /* _CFG_CAL_H */",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif /* __cplusplus */",
        "#include <stdint.h>",
        "",
        "/**",
        "* DID: 0xf011",
        f"* DID LEN: {did_len}",
        "* DID DESC(EN): Vehicle Configuration Data",
        "* DID DESC(EN):",
        "**/",
        "struct Did0xf011",
        "{",
    ]

    # Group items by byte number, preserving order within each byte
    byte_variables = OrderedDict()
    reserved_counter = 1

    for item in items:
        name = item.english_name or ""
        m = _RE_NUMBERED_RESERVED.match(name.strip())
        if m:
            reserved_counter = max(reserved_counter, int(m.group(1)) + 1)
        elif name == "RESERVED_" or item.is_reserved:
            name = f"RESERVED_{reserved_counter}"
            reserved_counter += 1

        byte_num = item.byte
        if byte_num not in byte_variables:
            byte_variables[byte_num] = []
        byte_variables[byte_num].append((item.type, name, item.bit_count))

    # DID 0xf011 is 24 bytes (0-23); fill gaps with 8-bit RESERVED_
    max_byte = 23
    if byte_variables:
        max_byte = max(max_byte, max(byte_variables.keys()))

    for byte_num in range(max_byte + 1):
        if byte_num in byte_variables:
            variables = byte_variables[byte_num]
            if bit_order == "reverse":
                variables = list(reversed(variables))
            for var_type, var_name, bit_width in variables:
                header_content.append(
                    f"    {var_type} {var_name} : {bit_width}; // Byte {byte_num}"
                )
        else:
            name = f"RESERVED_{reserved_counter}"
            reserved_counter += 1
            header_content.append(
                f"    uint8_t {name} : 8; // Byte {byte_num}"
            )

    header_content.extend([
        "};",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif /* __cplusplus */",
        "",
        "#endif /* _CFG_CAL_H */",
    ])

    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(header_content))
